language: ruby

rvm:
  - 2.2

script: "./script/ci_build.sh"

after_success:
  - script/deploy_gh_pages.sh

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - GH_PAGES_PRODUCTION_REF=github.com/alexpls/www.soonlistapp.com.git
    - secure: Go8oUFU9vFicL8ewNkjPKP28qOeo0it/xJRuGM7IaePEM7kZ/Kp+eY1QuJldcMhLLhrB2WuOnfTAD5DkXcU/O6R/pNAK1dyousUS9r/jXv58QkfGwN38ylZUjODmVWdu3dhIm1qiJj/t0xH2d5988s8N14bBvgntmWqhXuQMt0DmYBY3h1MyttJoL37HUL8NKGlhXSGsDYZ0eUSzq3EUnuoHgJ3fXuFPh4HX8bFHN/Vz3LMCXh55LGSJe18SxI/zmT7RHNLnmcVx9xCSK3hOd9YgF+yeUIK2c9qRqKTDZJzdbob/DV+TRel27boZ+tGR06YrU+/Qbje5qT3hSEhClwW/laHERgN6zcDFWMCZZRJtZ38GBK80IIVwR2M+PtP2KVto+Q36rN+XaYFqqVhCBXgm48q1UrIZ4qc7pR3pco1ym0GMAGGob+e/ysdkBby2i052XwIu70LpJLCMpCXpKoX7F8b6BidorqXrvBqi+YgubitEwJrTzE3uotIaecowgBLJlxEJGAaY15KMTJJc6y0cVpsZ18P371w1AzabmSe5lx4bffcNW8wxmHdfMUJIx8SaL9Wj2NSQvaL29D0Ms9gOGZ/tYlj0xth/jeKYQfWy2aFdX5QeF7CYj4ZpErTn0KzkObbRch1bY0+8taiDNlhqavWTTuj4s2MJ+fQ2cmw=
