title: Soonlist for iPhone - Upcoming movie release tracker and reminders
email: alex@alexplescan.com
description: >
  Soonlist is an iPhone app that helps you stay up to date with the upcoming movies
  you're interested in
baseurl: ""
url: "https://soonlistapp.com"

markdown: kramdown
