title: Soonlist for iPhone
email: alex@alexplescan.com
description: >
  Soonlist is an iPhone app that gives you information about upcoming movies, and
  reminds you when your favourite ones are coming out
baseurl: ""
url: "https://soonlistapp.com"

markdown: kramdown

exclude: [vendor, script, TODO.md, Gemfile, Gemfile.lock, README.md]

app_store_id: 1041801201
app_store_link: https://geo.itunes.apple.com/us/app/soonlist-upcoming-movie-info/id1041801201?mt=8

assets:
  autoprefixer:
    browsers: ["last 2 versions", "> 5%", "IE9"]
  assets:
    - "*.png"
  compress:
    css: true
    js: true

gems:
  - jekyll-assets
  - octopress-autoprefixer
