title: Soonlist for iPhone - Upcoming movie release tracker and reminders
email: alex@alexplescan.com
description: >
  Soonlist is an iPhone app that helps you stay up to date with the upcoming movies
  you're interested in
baseurl: ""
url: "https://soonlistapp.com"

markdown: kramdown

exclude: [vendor, script, TODO.md, Gemfile, Gemfile.lock]

app_store_id: 1041801201
app_store_link: https://geo.itunes.apple.com/us/app/soonlist-upcoming-movie-info/id1041801201?mt=8

assets:
  autoprefixer:
    browsers: ["last 2 versions", "> 5%", "IE9"]
  assets:
    - "*.png"

gems:
  - jekyll-assets
  - octopress-autoprefixer
